import type { BgmiLiteRedeemCodeItem } from "@/src/lib/bgmiLiteRedeemCodes";

/** Built-in illustrative codes (fan-made samples — replace via admin). */
export const DEFAULT_BGMI_LITE_REDEEM_CODES: BgmiLiteRedeemCodeItem[] = [
  {
    id: "lite-elite-992",
    title: "BGMI Global Series Crate Code",
    code: "BGMI-ELITE-992",
    status: "live",
    releasedLabel: "Released: 26 Aug, 02:30 PM",
    expiresLabel: "Expires: 27 Aug, 06:00 PM",
  },
  {
    id: "lite-uc-boost-01",
    title: "Lite UC Boost Weekend",
    code: "LITE-UC-BOOST-01",
    status: "live",
    releasedLabel: "Released: 28 Aug, 10:00 AM",
    expiresLabel: "Expires: 30 Aug, 11:59 PM",
  },
  {
    id: "lite-crate-drop-07",
    title: "Classic Crate Drop Pack",
    code: "LITE-CRATE-07",
    status: "live",
    releasedLabel: "Released: 27 Aug, 04:15 PM",
    expiresLabel: "Expires: 29 Aug, 09:00 PM",
  },
  {
    id: "lite-royale-pass",
    title: "Royale Pass XP Token",
    code: "LITE-RP-XP-884",
    status: "live",
    releasedLabel: "Released: 25 Aug, 12:00 PM",
    expiresLabel: "Expires: 01 Sep, 12:00 PM",
  },
  {
    id: "lite-prime-gift",
    title: "Prime Membership Gift",
    code: "LITE-PRIME-GIFT",
    status: "live",
    releasedLabel: "Released: 29 Aug, 08:30 AM",
    expiresLabel: "Expires: 31 Aug, 08:30 AM",
  },
  {
    id: "lite-squad-win",
    title: "Squad Win Celebration Pack",
    code: "SQUAD-WIN-LITE-26",
    status: "live",
    releasedLabel: "Released: 24 Aug, 07:00 PM",
    expiresLabel: "Expires: 28 Aug, 07:00 PM",
  },
  {
    id: "lite-miramar-run",
    title: "Miramar Survival Bundle",
    code: "MIRAMAR-LITE-55",
    status: "live",
    releasedLabel: "Released: 23 Aug, 03:00 PM",
    expiresLabel: "Expires: 30 Aug, 03:00 PM",
  },
  {
    id: "lite-erangel-air",
    title: "Erangel Airdrop Coupon",
    code: "ERANGEL-AIR-LITE",
    status: "live",
    releasedLabel: "Released: 22 Aug, 01:20 PM",
    expiresLabel: "Expires: 29 Aug, 01:20 PM",
  },
  {
    id: "lite-karakin-fast",
    title: "Karakin Fast Match Bonus",
    code: "KARAKIN-FAST-09",
    status: "live",
    releasedLabel: "Released: 21 Aug, 11:00 AM",
    expiresLabel: "Expires: 28 Aug, 11:00 AM",
  },
  {
    id: "lite-sanhok-heat",
    title: "Sanhok Heatwave Crate",
    code: "SANHOK-HEAT-33",
    status: "live",
    releasedLabel: "Released: 20 Aug, 05:45 PM",
    expiresLabel: "Expires: 27 Aug, 05:45 PM",
  },
  {
    id: "lite-vikendi-ice",
    title: "Vikendi Ice Skin Token",
    code: "VIKENDI-ICE-12",
    status: "live",
    releasedLabel: "Released: 19 Aug, 09:10 AM",
    expiresLabel: "Expires: 26 Aug, 09:10 AM",
  },
  {
    id: "lite-livik-flash",
    title: "Livik Flash Event Code",
    code: "LIVIK-FLASH-77",
    status: "live",
    releasedLabel: "Released: 18 Aug, 06:00 PM",
    expiresLabel: "Expires: 25 Aug, 06:00 PM",
  },
  {
    id: "lite-tdm-arena",
    title: "TDM Arena Reward Code",
    code: "TDM-ARENA-LITE",
    status: "live",
    releasedLabel: "Released: 17 Aug, 02:00 PM",
    expiresLabel: "Expires: 24 Aug, 02:00 PM",
  },
  {
    id: "lite-ranked-push",
    title: "Ranked Push Supply Box",
    code: "RANKED-PUSH-64",
    status: "live",
    releasedLabel: "Released: 16 Aug, 10:30 AM",
    expiresLabel: "Expires: 23 Aug, 10:30 AM",
  },
  {
    id: "lite-friend-invite",
    title: "Friend Invite Bonus Pack",
    code: "INVITE-LITE-2026",
    status: "live",
    releasedLabel: "Released: 15 Aug, 08:00 AM",
    expiresLabel: "Expires: 22 Aug, 08:00 AM",
  },
  {
    id: "lite-login-day7",
    title: "7-Day Login Streak Gift",
    code: "LOGIN7-LITE-OK",
    status: "live",
    releasedLabel: "Released: 14 Aug, 12:00 PM",
    expiresLabel: "Expires: 21 Aug, 12:00 PM",
  },
  {
    id: "lite-stream-watch",
    title: "Stream Watch Viewer Drop",
    code: "STREAM-DROP-LITE",
    status: "live",
    releasedLabel: "Released: 13 Aug, 07:30 PM",
    expiresLabel: "Expires: 20 Aug, 07:30 PM",
  },
  {
    id: "lite-clan-war",
    title: "Clan War Participation Box",
    code: "CLAN-WAR-LITE-8",
    status: "live",
    releasedLabel: "Released: 12 Aug, 04:00 PM",
    expiresLabel: "Expires: 19 Aug, 04:00 PM",
  },
  {
    id: "lite-emote-fun",
    title: "Fun Emote Unlock Token",
    code: "EMOTE-FUN-LITE",
    status: "live",
    releasedLabel: "Released: 11 Aug, 01:00 PM",
    expiresLabel: "Expires: 18 Aug, 01:00 PM",
  },
  {
    id: "lite-parachute",
    title: "Parachute Skin Trial Code",
    code: "PARA-TRIAL-41",
    status: "live",
    releasedLabel: "Released: 10 Aug, 09:45 AM",
    expiresLabel: "Expires: 17 Aug, 09:45 AM",
  },
  {
    id: "lite-vehicle-skin",
    title: "Vehicle Skin Weekend Pass",
    code: "VEHICLE-WKND-03",
    status: "live",
    releasedLabel: "Released: 09 Aug, 03:20 PM",
    expiresLabel: "Expires: 16 Aug, 03:20 PM",
  },
  {
    id: "lite-ammo-crate",
    title: "Ammo Crate Supply Code",
    code: "AMMO-CRATE-LITE",
    status: "live",
    releasedLabel: "Released: 08 Aug, 11:15 AM",
    expiresLabel: "Expires: 15 Aug, 11:15 AM",
  },
  {
    id: "lite-helmet-skin",
    title: "Helmet Skin Redeem Pack",
    code: "HELMET-SKIN-29",
    status: "live",
    releasedLabel: "Released: 07 Aug, 05:00 PM",
    expiresLabel: "Expires: 14 Aug, 05:00 PM",
  },
  {
    id: "lite-backpack",
    title: "Backpack Cosmetic Token",
    code: "BAG-COSMETIC-16",
    status: "live",
    releasedLabel: "Released: 06 Aug, 02:40 PM",
    expiresLabel: "Expires: 13 Aug, 02:40 PM",
  },
  {
    id: "lite-night-mode",
    title: "Night Mode Event Code",
    code: "NIGHT-MODE-LITE",
    status: "live",
    releasedLabel: "Released: 05 Aug, 08:00 PM",
    expiresLabel: "Expires: 12 Aug, 08:00 PM",
  },
  {
    id: "lite-gsh-promo",
    title: "Geneshots Special Promo Reward",
    code: "GSH-PROMO-2026",
    status: "live",
    releasedLabel: "Released: 04 Aug, 12:00 PM",
    expiresLabel: "Expires: 11 Aug, 12:00 PM",
  },
  {
    id: "lite-summer-fest",
    title: "Summer Fest Crate Code",
    code: "SUMMER-FEST-LITE",
    status: "live",
    releasedLabel: "Released: 03 Aug, 06:00 PM",
    expiresLabel: "Expires: 10 Aug, 06:00 PM",
  },
  {
    id: "lite-mono-week",
    title: "Monsoon Week Bonus Pack",
    code: "MONSOON-WEEK-5",
    status: "live",
    releasedLabel: "Released: 02 Aug, 09:00 AM",
    expiresLabel: "Expires: 09 Aug, 09:00 AM",
  },
  {
    id: "lite-aug-flash",
    title: "August Flash Sale UC Code",
    code: "AUG-FLASH-UC",
    status: "live",
    releasedLabel: "Released: 01 Aug, 11:00 AM",
    expiresLabel: "Expires: 08 Aug, 11:59 PM",
  },
  {
    id: "lite-july-vault",
    title: "July Vault Redeem Code",
    code: "JULY-VAULT-LITE",
    status: "live",
    releasedLabel: "Released: 30 Jul, 10:00 AM",
    expiresLabel: "Expires: 06 Aug, 10:00 AM",
  },
];
