import type { BgmiLiteRedeemCodeItem } from "@/src/lib/bgmiLiteRedeemCodes";

/** 30 illustrative expired archive codes (fan-made samples). */
export const DEFAULT_BGMI_LITE_REDEEM_EXPIRED_CODES: BgmiLiteRedeemCodeItem[] = [
  {
    id: "exp-gsh-old",
    title: "Geneshots Special Promo Reward",
    code: "GSH-OLD-2026-X",
    status: "expired",
    expiredOnLabel: "Expired on: 22 Aug, 12:00 PM",
  },
  {
    id: "exp-summer-fest",
    title: "Summer Fest Crate Code",
    code: "SUMMER-FEST-OLD",
    status: "expired",
    expiredOnLabel: "Expired on: 18 Aug, 06:00 PM",
  },
  {
    id: "exp-mono-week",
    title: "Monsoon Week Bonus Pack",
    code: "MONSOON-OLD-5",
    status: "expired",
    expiredOnLabel: "Expired on: 10 Aug, 09:00 AM",
  },
  {
    id: "exp-aug-flash",
    title: "August Flash Sale UC Code",
    code: "AUG-FLASH-OLD",
    status: "expired",
    expiredOnLabel: "Expired on: 05 Aug, 11:59 PM",
  },
  {
    id: "exp-july-vault",
    title: "July Vault Redeem Code",
    code: "JULY-VAULT-OLD",
    status: "expired",
    expiredOnLabel: "Expired on: 31 Jul, 11:59 PM",
  },
  {
    id: "exp-mid-july",
    title: "Mid-July Login Gift",
    code: "MIDJULY-GIFT-1",
    status: "expired",
    expiredOnLabel: "Expired on: 20 Jul, 08:00 PM",
  },
  {
    id: "exp-squad-june",
    title: "June Squad Challenge Box",
    code: "JUNE-SQUAD-88",
    status: "expired",
    expiredOnLabel: "Expired on: 30 Jun, 11:59 PM",
  },
  {
    id: "exp-rain-drop",
    title: "Rain Drop Event Crate",
    code: "RAIN-DROP-42",
    status: "expired",
    expiredOnLabel: "Expired on: 25 Jun, 04:00 PM",
  },
  {
    id: "exp-heatwave",
    title: "Heatwave Weekend Pack",
    code: "HEATWAVE-WK-09",
    status: "expired",
    expiredOnLabel: "Expired on: 15 Jun, 10:00 AM",
  },
  {
    id: "exp-clan-may",
    title: "May Clan War Reward",
    code: "MAY-CLAN-WAR",
    status: "expired",
    expiredOnLabel: "Expired on: 31 May, 11:59 PM",
  },
  {
    id: "exp-mirror-match",
    title: "Mirror Match Bonus Code",
    code: "MIRROR-MATCH-7",
    status: "expired",
    expiredOnLabel: "Expired on: 20 May, 07:30 PM",
  },
  {
    id: "exp-arena-cup",
    title: "Arena Cup Viewer Drop",
    code: "ARENA-CUP-DROP",
    status: "expired",
    expiredOnLabel: "Expired on: 10 May, 01:00 PM",
  },
  {
    id: "exp-spring-crate",
    title: "Spring Crate Redeem Pack",
    code: "SPRING-CRATE-3",
    status: "expired",
    expiredOnLabel: "Expired on: 30 Apr, 11:59 PM",
  },
  {
    id: "exp-april-fool",
    title: "April Fun Emote Token",
    code: "APRIL-FUN-01",
    status: "expired",
    expiredOnLabel: "Expired on: 07 Apr, 12:00 PM",
  },
  {
    id: "exp-holi-color",
    title: "Holi Color Splash Pack",
    code: "HOLI-COLOR-26",
    status: "expired",
    expiredOnLabel: "Expired on: 20 Mar, 09:00 PM",
  },
  {
    id: "exp-womens-day",
    title: "Women's Day Gift Code",
    code: "WD-GIFT-2026",
    status: "expired",
    expiredOnLabel: "Expired on: 10 Mar, 11:59 PM",
  },
  {
    id: "exp-feb-valentine",
    title: "Valentine Duo Bundle",
    code: "VAL-DUO-14",
    status: "expired",
    expiredOnLabel: "Expired on: 16 Feb, 11:59 PM",
  },
  {
    id: "exp-republic",
    title: "Republic Day Parade Crate",
    code: "REPUBLIC-26-CR",
    status: "expired",
    expiredOnLabel: "Expired on: 28 Jan, 08:00 PM",
  },
  {
    id: "exp-new-year",
    title: "New Year Fireworks Pack",
    code: "NY-FIRE-2026",
    status: "expired",
    expiredOnLabel: "Expired on: 07 Jan, 11:59 PM",
  },
  {
    id: "exp-xmas",
    title: "Christmas Snow Bundle",
    code: "XMAS-SNOW-25",
    status: "expired",
    expiredOnLabel: "Expired on: 31 Dec, 11:59 PM",
  },
  {
    id: "exp-winter-fest",
    title: "Winter Fest Supply Box",
    code: "WINTER-FEST-25",
    status: "expired",
    expiredOnLabel: "Expired on: 20 Dec, 06:00 PM",
  },
  {
    id: "exp-black-friday",
    title: "Black Friday Flash Code",
    code: "BF-FLASH-25",
    status: "expired",
    expiredOnLabel: "Expired on: 30 Nov, 11:59 PM",
  },
  {
    id: "exp-diwali",
    title: "Diwali Lights Crate Code",
    code: "DIWALI-LIGHT-25",
    status: "expired",
    expiredOnLabel: "Expired on: 05 Nov, 11:59 PM",
  },
  {
    id: "exp-halloween",
    title: "Halloween Spook Pack",
    code: "HALLOWEEN-25",
    status: "expired",
    expiredOnLabel: "Expired on: 01 Nov, 12:00 AM",
  },
  {
    id: "exp-dussehra",
    title: "Dussehra Victory Bundle",
    code: "DUSSEHRA-25-V",
    status: "expired",
    expiredOnLabel: "Expired on: 10 Oct, 09:00 PM",
  },
  {
    id: "exp-sep-ranked",
    title: "September Ranked Push Box",
    code: "SEP-RANKED-25",
    status: "expired",
    expiredOnLabel: "Expired on: 30 Sep, 11:59 PM",
  },
  {
    id: "exp-teacher-day",
    title: "Teachers Day Thank You Pack",
    code: "TEACHER-DAY-25",
    status: "expired",
    expiredOnLabel: "Expired on: 07 Sep, 11:59 PM",
  },
  {
    id: "exp-independence",
    title: "Independence Day Crate",
    code: "INDEP-DAY-25",
    status: "expired",
    expiredOnLabel: "Expired on: 17 Aug, 11:59 PM",
  },
  {
    id: "exp-rakhi",
    title: "Raksha Bandhan Duo Pack",
    code: "RAKHI-DUO-25",
    status: "expired",
    expiredOnLabel: "Expired on: 12 Aug, 11:59 PM",
  },
  {
    id: "exp-friendship",
    title: "Friendship Day Invite Code",
    code: "FRIEND-DAY-25",
    status: "expired",
    expiredOnLabel: "Expired on: 05 Aug, 11:59 PM",
  },
];
